/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.ControlAssunto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Assunto;
import model.bean.Disciplina;
import model.dao.DisciplinaDAO;

/**
 *
 * @author mmano
 */
public class AdicionarAssunto extends javax.swing.JFrame {

    /**
     * Creates new form Add_Questao
     */
    public AdicionarAssunto() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtableMateria.getModel();
        jtableMateria.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMateria = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableAssunto = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar Assunto");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-icon.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 40, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 405, 391));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon-assuntos.png"))); // NOI18N
        jLabel2.setText("Adicionar Assunto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 40, 517, 46));

        jtableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matéria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMateriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableMateria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 164, 176, 118));

        jLabel3.setText("Selecione uma matéria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 144, -1, -1));

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 288, -1, -1));

        jLabel5.setText("Assuntos:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 144, -1, -1));

        jtableAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Assunto"
            }
        ));
        jScrollPane2.setViewportView(jtableAssunto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 164, 331, 118));

        jButton2.setText("Deletar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(855, 288, -1, -1));

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 288, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        try {
            
            
            if(jtableMateria.getSelectedRow() != -1) {
                String nome_assunto = JOptionPane.showInputDialog("Digite um Assunto");

                Integer fk_materia = (int) jtableMateria.getValueAt(jtableMateria.getSelectedRow(), 0);
                
                ControlAssunto cProva = new ControlAssunto();
                cProva.adicionarAssunto(nome_assunto, fk_materia);
  
            } else {
                JOptionPane.showMessageDialog(null, "Selecione alguma matéria");
            }
                    
           
        } catch(Exception error) {
            JOptionPane.showMessageDialog(null, "Por favor selecione alguma matéria");
        }
        

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtableMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMateriaMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jtableAssunto.getModel();
        
        if(jtableMateria.getSelectedRow() != -1) {
            modelo.setNumRows(0);
            Integer id = (int) jtableMateria.getValueAt(jtableMateria.getSelectedRow(), 0);
            readJTableAssuntosForId(id);
        }
    }//GEN-LAST:event_jtableMateriaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ControlAssunto cProva = new ControlAssunto();
        
        if(jtableMateria.getSelectedRow() != -1 && jtableAssunto.getSelectedRow() != -1) {
            Integer id = (int) jtableAssunto.getValueAt(jtableAssunto.getSelectedRow(), 0);
            cProva.deletarAssunto(id);
       
        } else {
            JOptionPane.showMessageDialog(null, "Selecione alguma matéria ou um assunto!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ControlAssunto cProva = new ControlAssunto();
        DefaultTableModel modelo = (DefaultTableModel) jtableAssunto.getModel();
        
        
        if(jtableMateria.getSelectedRow() != -1 && jtableAssunto.getSelectedRow() != -1) {
            String alterar_assunto = JOptionPane.showInputDialog("Altere o nome do assunto");
            
            JOptionPane.showMessageDialog(null, "Nome alterado com sucesso");
            Integer id = (int) jtableAssunto.getValueAt(jtableAssunto.getSelectedRow(), 0);
            cProva.editarAssunto(id, alterar_assunto);
            modelo.setNumRows(0);
                   
        } else {
            JOptionPane.showMessageDialog(null, "Há algo de errado.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Prof prof = new Prof();
        prof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarAssunto().setVisible(true);
            }
        });
    }
    
    
    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) jtableMateria.getModel();
        
        DisciplinaDAO discDAO = new DisciplinaDAO();
        
        for(Disciplina disc: discDAO.Read()) {
            modelo.addRow(new Object[]{
                disc.getCodigo(),
                disc.getNome()
           
            });
            
        }   
    }
        
        
    public void readJTableAssuntosForId(int id) {
        DefaultTableModel modelo = (DefaultTableModel) jtableAssunto.getModel();
        
        ControlAssunto cProva = new ControlAssunto(); 
        
        for(Assunto As: cProva.listarPorMateria(id)) {
            modelo.addRow(new Object[]{
                As.getId(),
                As.getNome()
            });
        
    }
        
        
        
     
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtableAssunto;
    private javax.swing.JTable jtableMateria;
    // End of variables declaration//GEN-END:variables
}
