/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControlAssunto;
import controller.ControlProva;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Assunto;
import model.bean.Disciplina;
import model.bean.Prova;
import model.bean.Questao;
import model.bean.Usuario;
import model.dao.DisciplinaDAO;

/**
 *
 * @author mmano
 */
public class CadastrarQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form Gerar_Prova
     */
    public CadastrarQuestoes() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tableMateria.getModel();
        tableMateria.setRowSorter(new TableRowSorter(modelo));
        readJTableMaterias();
        
        // Iniciar Listagem do JComboBox
        
        ControlProva cProva = new ControlProva();
        
        for(Prova p : cProva.listarProvas()) {
            listarProva.addItem(p.getId() + " " + p.getNome_prova());
            
        } 
        
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMateria = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAssunto = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        enunciado = new javax.swing.JTextField();
        item_c = new javax.swing.JTextField();
        item_b = new javax.swing.JTextField();
        item_a = new javax.swing.JTextField();
        item_d = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        listarProva = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuestoes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Questões");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 40, 50));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.png"))); // NOI18N
        jPanel4.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 396, 482));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/questions-icon.png"))); // NOI18N
        jLabel1.setText("Cadastrar Questões");

        tableMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matéria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMateriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMateria);

        tableAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Assunto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAssunto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAssuntoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableAssunto);

        jLabel2.setText("Cadastro de questões:");

        jLabel4.setText("Selecione uma matéria:");

        jLabel5.setText("Selecione um assunto:");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enunciado");

        jLabel7.setText("Item A");

        jLabel8.setText("Item B");

        jLabel9.setText("Item C");

        jLabel10.setText("Item D");

        listarProva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarProvaMouseClicked(evt);
            }
        });
        listarProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(item_a, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(41, 41, 41)
                                                .addComponent(jLabel7)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item_b, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(item_c, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)))
                                    .addComponent(listarProva, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jLabel10)
                                    .addComponent(item_d, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(listarProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 11, -1, -1));

        tableQuestoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Enunciado", "Item A", "Item B", "Item C", "Item D"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuestoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuestoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuestoes);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 393, 537, 90));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 479));

        jButton2.setText("Apagar Questão");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 485, -1, -1));

        jButton4.setText("Editar Questão");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(721, 485, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tableMateria.getSelectedRow() != -1 && tableAssunto.getSelectedRow() != -1) {
            ControlProva cProva = new ControlProva();
            String enunciado = this.enunciado.getText();
            String item_a = this.item_a.getText();
            String item_b = this.item_b.getText();
            String item_c = this.item_c.getText();
            String item_d = this.item_d.getText();
            
            if(!enunciado.trim().isEmpty() && !item_a.trim().isEmpty() && !item_b.trim().isEmpty() && 
                !item_c.trim().isEmpty() && !item_d.trim().isEmpty()) {
                Integer id_assunto = (int) tableAssunto.getValueAt(tableAssunto.getSelectedRow(), 0);
                String item_selecionado = String.valueOf(listarProva.getSelectedItem());
                String [] id_prova = item_selecionado.split(" ");
                Integer id_convetido = Integer.parseInt(id_prova[0]);

                cProva.cadastrarProva(enunciado, item_a, item_b, item_c, item_d, id_assunto, id_convetido);
                
                this.enunciado.setText("");
                this.item_a.setText("");
                this.item_b.setText("");
                this.item_c.setText("");
                this.item_d.setText("");
                
            } else {
                JOptionPane.showMessageDialog(null, "Por favor preencha todos os inputs.");
                
            }
           
         
            
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione os dados das tabelas acima.");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMateriaMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tableAssunto.getModel();
        
        if(tableMateria.getSelectedRow() != -1) {
            modelo.setNumRows(0);
            Integer id = (int) tableMateria.getValueAt(tableMateria.getSelectedRow(), 0);
            readJTableAssuntosForId(id);
        }
    }//GEN-LAST:event_tableMateriaMouseClicked

    private void tableAssuntoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAssuntoMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) tableQuestoes.getModel();
        try {
            if(tableAssunto.getSelectedRow() != -1) {
                modelo.setNumRows(0);
                Integer id = (int) tableAssunto.getValueAt(tableAssunto.getSelectedRow(), 0);
                readJTableQuestoesById(id);
                
        
           
            }
            
        } catch(Exception error) {
            JOptionPane.showMessageDialog(null, "Erro: " + error);
        }
        
          
        
    }//GEN-LAST:event_tableAssuntoMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Editar questão
        ControlProva cProva = new ControlProva();
        String enunciado = this.enunciado.getText();
        String item_a = this.item_a.getText();
        String item_b = this.item_b.getText();
        String item_c = this.item_c.getText();
        String item_d = this.item_d.getText();
        Integer id = (int) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 0);
        cProva.editarQuestao(id, enunciado, item_a, item_b, item_c, item_d);
        JOptionPane.showMessageDialog(null, "Questão editada com sucesso!");
        
        this.enunciado.setText("");
        this.item_a.setText("");
        this.item_b.setText("");
        this.item_c.setText("");
        this.item_d.setText("");
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void listarProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProvaActionPerformed
        
    }//GEN-LAST:event_listarProvaActionPerformed

    private void listarProvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarProvaMouseClicked
      
    }//GEN-LAST:event_listarProvaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Apagar Questão
        if(tableQuestoes.getSelectedRow() != -1) {
            ControlProva cProva = new ControlProva();
            int id = (int) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 0);
            cProva.apagarQuestao(id);
            JOptionPane.showMessageDialog(null, "Questão apagada com sucesso");
                 
            
            this.enunciado.setText("");
            this.item_a.setText("");
            this.item_b.setText("");
            this.item_c.setText("");
            this.item_d.setText("");
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione alguma questão para ser apagada");
            
        }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Prof Prof = new Prof();
        Prof.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jLabel3MouseClicked

    private void tableQuestoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuestoesMouseClicked
        // Preencher dados no input para edição
        try {
            String enunciado_table = (String)tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 1);
            String resposta_a_table = (String) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 2);
            String resposta_b_table = (String) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 3);
            String resposta_c_table = (String) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 4);
            String resposta_d_table = (String) tableQuestoes.getValueAt(tableQuestoes.getSelectedRow(), 5);

            this.enunciado.setText(enunciado_table);
            this.item_a.setText(resposta_a_table);
            this.item_b.setText(resposta_b_table);
            this.item_c.setText(resposta_c_table);
            this.item_d.setText(resposta_d_table);
            
        } catch(Exception error) {
            JOptionPane.showMessageDialog(this, "Houve algum erro. Erro " + error);
        }
           
    }//GEN-LAST:event_tableQuestoesMouseClicked
    
     public void readJTableMaterias() {
        DefaultTableModel modelo = (DefaultTableModel) tableMateria.getModel();
        
        DisciplinaDAO discDAO = new DisciplinaDAO();
        
        for(Disciplina disc: discDAO.Read()) {
            modelo.addRow(new Object[]{
                disc.getCodigo(),
                disc.getNome()
           
            });
            
        }   
    }
     
     
     public void readJTableQuestoesById(int id) {
         DefaultTableModel modelo = (DefaultTableModel) tableQuestoes.getModel();
         ControlProva cProva = new ControlProva();
         
        for(Questao p: cProva.consultarProvaPorId(id)) {
            modelo.addRow(new Object[] {
                p.getId(),
                p.getEnunciado(),
                p.getResposta_a(),
                p.getResposta_b(),
                p.getResposta_c(),
                p.getResposta_d()
            });
            
        } 
     }
     
       public void readJTableAssuntosForId(int id) {
        DefaultTableModel modelo = (DefaultTableModel) tableAssunto.getModel();
        
        ControlAssunto cProva = new ControlAssunto(); 
        
        for(Assunto As: cProva.listarPorMateria(id)) {
            modelo.addRow(new Object[]{
                As.getId(),
                As.getNome()
            }); 
    }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField enunciado;
    private javax.swing.JTextField item_a;
    private javax.swing.JTextField item_b;
    private javax.swing.JTextField item_c;
    private javax.swing.JTextField item_d;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> listarProva;
    private javax.swing.JTable tableAssunto;
    private javax.swing.JTable tableMateria;
    private javax.swing.JTable tableQuestoes;
    // End of variables declaration//GEN-END:variables
}
